<?php
/**
 * @author Maxim Cherednyk <maks757q@gmail.com, +380639960375>
 */

namespace bl\honors;


use bl\honors\behaviors\Honor;
use yii\base\Component;

class HonorsComponent extends Component
{
    public function behaviors()
    {
        return [
            'honor' => [
                'class' => Honor::className()
            ]
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}